spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "1234"

  sql:
    init:
      continue-on-error: "true"
  jpa:
    hibernate:
      ddl-auto: "validate"
server:
  port: 8090